export const FETCH_DELETE_PAYMENT_REQUEST = "FETCH_DELETE_PAYMENT_REQUEST";
export const FETCH_DELETE_PAYMENT_SUCCESS = "FETCH_DELETE_PAYMENT_SUCCESS";
export const FETCH_DELETE_PAYMENT_FAILURE = "FETCH_DELETE_PAYMENT_FAILURE";
