export const FETCH_ADD_PAYMENT_REQUEST = "FETCH_ADD_PAYMENT_REQUEST";
export const FETCH_ADD_PAYMENT_SUCCESS = "FETCH_ADD_PAYMENT_SUCCESS";
export const FETCH_ADD_PAYMENT_FAILURE = "FETCH_ADD_PAYMENT_FAILURE";
