export const FETCH_ACTIVE_PAYMENT_REQUEST = "FETCH_ACTIVE_PAYMENT_REQUEST";
export const FETCH_ACTIVE_PAYMENT_SUCCESS = "FETCH_ACTIVE_PAYMENT_SUCCESS";
export const FETCH_ACTIVE_PAYMENT_FAILURE = "FETCH_ACTIVE_PAYMENT_FAILURE";
