export const FETCH_EDIT_PAYMENT_REQUEST = "FETCH_EDIT_PAYMENT_REQUEST";
export const FETCH_EDIT_PAYMENT_SUCCESS = "FETCH_EDIT_PAYMENT_SUCCESS";
export const FETCH_EDIT_PAYMENT_FAILURE = "FETCH_EDIT_PAYMENT_FAILURE";
