export const FETCH_GET_PAYMENT_LIST_REQUEST = "FETCH_GET_PAYMENT_LIST_REQUEST";
export const FETCH_GET_PAYMENT_LIST_SUCCESS = "FETCH_GET_PAYMENT_LIST_SUCCESS";
export const FETCH_GET_PAYMENT_LIST_FAILURE = "FETCH_GET_PAYMENT_LIST_FAILURE";
